### ISSUE TITLE
Compiling issue due to different use of capitals in file names and includes

### ISSUE THREAD

**Issue by bremme** [SimuCUBE/SimuCUBE-OpenSource-Firmware#1]
I own a SimuCUBE based OSW wheel (Simplicity SW20 v2). I read that you guys were going to open source (parts) of the SimuCUBE firmware. I'm currently in the process of connecting all/most of my inputs devices (pedals, shifter, buttonplate/boxes etc) directly to the SimuCUBE. I figured I might need some modifications to the firmware so I just had a look.

I have some experience with C/C++ and micro controllers (mainly Arduino, platformio and a little mbed), but not (yet) so much with your toolchain, Atollic Studio. So far for the introduction:)

I just made a clone off the latest commit (e745f09380cb2b13d43a2f4aae94eaf9379d08e2) on the master branch, installed Atollic Studio (on Debian), selected one of the suggested build configurations (Debug-normal-opensource) and tried to build. I ran into a couple problems. Several included seem to use the wrong name for the file they try to include. I renamed the following:

| Old include                     | Renamed to                     |
| :------------------------------ | :----------------------------- |
| #include <ffbengine.h>          | #include <FfbEngine.h>         | 
| #include "eventlog.h"           | #include "eventLog.h"          |  
| #include "usbgamecontroller.h"  | #include "USBGameController.h" |
| #include <Math.h>               | #include <math.h>              | 

Is this a problem with the latest commit, or did I made a mistake in my configuration?

Another question, maybe a little off topic. But I also noticed that the latest commit is at version `0.10.3` of the SimuCUBE firmware, while `0.11.3` has been released already? When will this repository get updated to the latest release (I'm particularly interested in the additional button and encoder support).

**Comment by mtakala** [comment]
Hi!

Finally I'm allowed to speak. We didn't have the repository in a state where we would be comfortable in pushing the code to open source, as we were developing so much stuff simultaneously.

The next public version will be pushed here as well.

The filename case issues are something that only Linux seems to pick up, and we have stumbled upon them as well.

**Comment by bremme** [comment]
Hi @mtakala, thanks for your reply! I was getting a bit worried on the open source development of the firmware, good to hear a more up to date release is coming. I guess its hard to give an exact date, but are we talking days, weeks or months for a new release to be pushed?

Next time I will install the toolchain on a Windows machine to see if that works better. Probably makes more sense since I do my gaming on Windows anyway.

**Comment by mtakala** [comment]
Our current code ( to be pushed here soon ) solves the linux/windows issue.
