### ISSUE TITLE
Custom steering lock issue

### ISSUE THREAD

**Issue by gro-ove** [SimuCUBE/SimuCUBE-OpenSource-Firmware#2]
I’m working on a custom launcher for Assetto Corsa and recently there were quite a few reports about steering lock no longer working with SimuCUBE devices. Could you please check if example in this repo is up to date? I believe [my implementation](https://github.com/gro-ove/actools/blob/master/AcTools.WheelAngles/Implementations/SimuCube.cs) of it is accurate.

**Comment by mtakala** [comment]
I will check!

We just released new Simucube products. It would be nice if you could add the following Product ID:s to your software:
0x0D5F, 0x0D60 and 0x0D61

**Comment by gro-ove** [comment]
Thank you, and I sure will add those, thanks for that too!

**Comment by mtakala** [comment]
I can confirm, that the API is unchanged from this version in the repository. So, it might be a bug on the firmware side too. I will test this personally before next release.

**Comment by mtakala** [comment]
I did investigate this last summer and didn't find any issue. Are there any recent reports about this?

**Comment by gro-ove** [comment]
Nope, so I believe it’s fixed now. Thank you!
